### ISSUE TITLE
Generated files and folders don't appear into vscode explorer

### ISSUE THREAD

**Issue by alete89** [abdullahceylan/vscode-react-component-generator#3]
I wasn't sure if I was supposed to report this here or in vscode.

Creating componentes from context menu inside a folder does not trigger an explorer update (as I can see in the GIFs you've made).
A workaround I found is creating a new file or folder from vscode's native context menu, that triggers an update and all files and folders created by the extension appear. 

Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-9-amd64

![vol](https://user-images.githubusercontent.com/4999277/57002457-e652dc80-6b95-11e9-8df4-4c6a10ed155f.gif)

Another possible issue that can be seing in the gif is that you can create a component named just like another one that already exists, and that would overwrite the existing.

**Comment by abdullahceylan** [comment]
@alete89 I've tested with VSCode 1.51.1 and couldn't see any issue. It might be related to your VSCode installation or another extension.
