### ISSUE TITLE
Can not install in VS Code. And these is no version compatible with Vs Code 1.24.1.

### ISSUE THREAD

**Issue by JaylyLiu** [abdullahceylan/vscode-react-component-generator#4]
![image](https://user-images.githubusercontent.com/21221455/57287869-f8c79b80-70ea-11e9-9ca7-157ad43d3bba.png)

**Comment by abdullahceylan** [comment]
@JaylyLiu, I'm not sure what says that error exactly but I'm able to use the extension with VSCode 1.51.1.
