### ISSUE TITLE
I can't make a Configuration on style extension, I need to support "ts" extension 

### ISSUE THREAD

**Issue by abdRumman** [abdullahceylan/vscode-react-component-generator#5]
when I open a configuration I can't select "ts" as a type of style file could you please add this extension to the list ? 
![image](https://user-images.githubusercontent.com/32413587/64797101-816ab280-d589-11e9-865e-99e31e950da0.png)

**Comment by abdullahceylan** [comment]
This is solved in v0.0.5 which is released now.

https://marketplace.visualstudio.com/items?itemName=abdullahceylan.vscode-react-component-generator
